### ISSUE TITLE
Map lts versions to semver in travis rule

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#66]
We now also support the nvm aliases `lts/argon` (Node.js 4) and `lts/boron` (Node.js 6). Currently the `travis` rule does not prevent something like this.

```json
{
    "name": "my-module",
    "engines": {
        "node": ">=6"
    }
}
```

```yml
language: node_js
node_js:
  - lts/boron
  - lts/argon
```

The rule should fail indicating that `lts/argon` is not supported. This can be done by mapping these aliases their semantic version equivalent and work from that.
