### ISSUE TITLE
Travis fails on fixing `node` and `stable` versions

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#73]
```yml
language: node_js
node_js:
  - 'stable'
  - 'node'
  - '0.12'
  - '0.10'
```
